Repository thomasbryk/4806_Project, pull requests merged in 2020-03, with the labels that each got.

#35 Rest Controller tests
  src/main/java/controllers/BookstoreRestController.java
  src/main/java/models/Sale.java
  src/test/java/BookstoreRestTest.java
  src/test/java/TestingWebAppTest.java
Labels: backend

#31 REST
  .idea/compiler.xml
  src/main/java/controllers/BookstoreRestController.java
  src/main/java/models/Book.java
  src/main/java/models/Bookstore.java
  src/main/java/models/BookstoreOwner.java
  src/main/java/models/Customer.java
  src/main/java/models/Sale.java
  src/main/java/models/ShoppingCart.java
  src/main/java/repositories/BookRepository.java
  src/main/java/repositories/SaleRepository.java
  src/main/java/repositories/ShoppingCartRepository.java
  src/test/java/BookstoreRestTest.java
  src/test/java/TestingWebAppTest.java
Labels: backend

#41 Dclaremont/milestone2/unit tests
  README.md
  src/main/java/controllers/BookstoreDevWebController.java
  src/main/java/models/Book.java
  src/main/java/models/Bookstore.java
  src/main/java/models/BookstoreOwner.java
  src/main/java/models/ShoppingCart.java
  src/test/java/BookTest.java
  src/test/java/BookstoreOwnerTest.java
  src/test/java/BookstoreTest.java
  src/test/java/CustomerTest.java
  src/test/java/SaleTest.java
  src/test/java/ShoppingCartTest.java
  src/test/java/TestSuite.java
Labels: backend

#43 Adjust unit tests for the refactor of Customer + BookstoreOwner in Auth branch
  src/main/java/controllers/BookstoreDevWebController.java
  src/main/java/models/Book.java
  src/main/java/models/Bookstore.java
  src/main/java/models/BookstoreOwner.java
  src/main/java/models/ShoppingCart.java
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/test/java/BookTest.java
  src/test/java/BookstoreOwnerTest.java
  src/test/java/BookstoreTest.java
  src/test/java/CustomerTest.java
  src/test/java/SaleTest.java
  src/test/java/ShoppingCartTest.java
  src/test/java/TestSuite.java
Labels: enhancement

#45 Bookstore book removal bug fix
  src/main/java/models/Bookstore.java
  src/main/resources/templates/editBookstore.html
  src/test/java/BookstoreTest.java
Labels: bug

#48 Adjust unit tests for the refactor of Customer + BookstoreOwner in Auth branch (2)
  src/main/java/models/Bookstore.java
  src/main/resources/templates/editBookstore.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/test/java/BookstoreOwnerTest.java
  src/test/java/BookstoreTest.java
  src/test/java/CustomerTest.java
Labels: enhancement

#51 Change name of back button when shopping a store in the dev portal
  src/main/resources/templates/shopBookstore.html
Labels: backend

#40 Auth
  .travis.yml
  pom.xml
  src/main/java/application/WebLauncher.java
  src/main/java/controllers/BookstoreDevWebController.java
  src/main/java/controllers/BookstoreRestController.java
  src/main/java/models/Bookstore.java
  src/main/java/models/BookstoreOwner.java
  src/main/java/models/BookstoreUser.java
  src/main/java/models/Customer.java
  src/main/java/repositories/BookstoreOwnerRepository.java
  src/main/java/repositories/CustomerRepository.java
  src/main/java/security/BasicConfiguration.java
  src/main/java/security/CustomAuthenticationSuccessHandler.java
  src/main/java/security/SessionConfig.java
  src/main/java/security/UserServiceDetails.java
  src/main/resources/application.properties
  src/main/resources/templates/accessDenied.jsp
  src/main/resources/templates/editBookstore.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/shopBookstore.html
  src/main/resources/templates/viewBookstoreOwner.html
  src/main/resources/templates/viewCustomer.html
  src/test/java/BookstoreOwnerTest.java
  src/test/java/BookstoreRestTest.java
  src/test/java/BookstoreTest.java
  src/test/java/CustomerTest.java
Labels: enhancement

#57 Convert collection of books in bookstore to a Set
  src/main/java/models/Bookstore.java
  src/test/java/BookstoreRestTest.java
Labels: bug

#58 Milestone 2 -> Master
  .travis.yml
  README.md
  pom.xml
  src/main/java/application/WebLauncher.java
  src/main/java/controllers/BookstoreDevWebController.java
  src/main/java/controllers/BookstoreRestController.java
  src/main/java/models/Book.java
  src/main/java/models/Bookstore.java
  src/main/java/models/BookstoreOwner.java
  src/main/java/models/BookstoreUser.java
  src/main/java/models/Customer.java
  src/main/java/models/ShoppingCart.java
  src/main/java/repositories/BookstoreOwnerRepository.java
  src/main/java/repositories/CustomerRepository.java
  src/main/java/security/BasicConfiguration.java
  src/main/java/security/CustomAuthenticationSuccessHandler.java
  src/main/java/security/SessionConfig.java
  src/main/java/security/UserServiceDetails.java
  src/main/resources/application.properties
  src/main/resources/templates/accessDenied.jsp
  src/main/resources/templates/editBookstore.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/shopBookstore.html
  src/main/resources/templates/viewBookstoreOwner.html
  src/main/resources/templates/viewCustomer.html
  src/test/java/BookTest.java
  src/test/java/BookstoreOwnerTest.java
  src/test/java/BookstoreRestTest.java
  src/test/java/BookstoreTest.java
  src/test/java/CustomerTest.java
  src/test/java/SaleTest.java
  src/test/java/ShoppingCartTest.java
  src/test/java/TestSuite.java
  uml/DatabaseSchema.docx
  uml/DatabaseSchema.png
  uml/UML_ClassDiagram.drawio
  uml/UML_ClassDiagram.png
Labels: backend, front-end
